### ISSUE TITLE
Color picker in the Interfacer returns wrong results

### ISSUE THREAD

**Issue by thalhofer** [korsakow/korsakow-editor#80]
Sometimes it works, sometimes is does not.

Example:
selected color
![screen shot 2016-06-07 at 17 49 21](https://cloud.githubusercontent.com/assets/6237236/15864786/b1d757dc-2cd8-11e6-9086-0344083e1563.png)

resulting color:
![screen shot 2016-06-07 at 17 49 34](https://cloud.githubusercontent.com/assets/6237236/15864810/cc102a0c-2cd8-11e6-9bda-e32cee1eb8c5.png)

**Comment by thalhofer** [comment]
You can not set the BG color to transparent. Can you?

**Comment by dreisch** [comment]
No, I’ll have to look into the color picker we’re using, sadly its the main blocker unless we do it as a separate property.
